# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"^\n\x0cTrainRequest\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x14\n\x0clocal_epochs\x18\x02 \x01(\x05\x12\x15\n\rlearning_rate\x18\x03 \x01(\x02\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\"0\n\x0bTestRequest\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"G\n\nTrainReply\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x15\n\ravg_trainloss\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x61taset_len\x18\x03 \x01(\x05\"E\n\tTestReply\x12\x11\n\teval_loss\x18\x01 \x01(\x02\x12\x10\n\x08\x65val_acc\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x61taset_len\x18\x03 \x01(\x05\x32Q\n\x08Training\x12#\n\x05Train\x12\r.TrainRequest\x1a\x0b.TrainReply\x12 \n\x04Test\x12\x0c.TestRequest\x1a\n.TestReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST']._serialized_start=14
  _globals['_TRAINREQUEST']._serialized_end=108
  _globals['_TESTREQUEST']._serialized_start=110
  _globals['_TESTREQUEST']._serialized_end=158
  _globals['_TRAINREPLY']._serialized_start=160
  _globals['_TRAINREPLY']._serialized_end=231
  _globals['_TESTREPLY']._serialized_start=233
  _globals['_TESTREPLY']._serialized_end=302
  _globals['_TRAINING']._serialized_start=304
  _globals['_TRAINING']._serialized_end=385
# @@protoc_insertion_point(module_scope)
