services:
  # create a SuperLink service
  superlink:
    image: flwr/superlink:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --isolation
      - process
    ports:
      - 9093:9093
    networks:
      - flower-net

  # create a SuperExec service for SuperLink to execute ServerApps
  superexec-serverapp:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: Dockerfile.server
      args:
        FLWR_VERSION: ${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --plugin-type
      - serverapp
      - --appio-api-address
      - superlink:9091
    network_mode: "service:superlink"
    restart: on-failure:3
    depends_on:
      - superlink
    volumes:
      - ./server:/home

  # create SuperNode services with different node configs
  supernode-1:
    image: flwr/supernode:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
      - --node-config
      - "partition-id=0 num-partitions=4 dataset-path='/home/partition_0.npz'"
    depends_on:
      - superlink
    volumes:
      - ./client_1:/home
    networks:
      - flower-net

  supernode-2:
    image: flwr/supernode:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9095
      - --isolation
      - process
      - --node-config
      - "partition-id=1 num-partitions=4 dataset-path='/home/partition_1.npz'"
    depends_on:
      - superlink
    volumes:
      - ./client_2:/home
    networks:
      - flower-net

  supernode-3:
    image: flwr/supernode:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9096
      - --isolation
      - process
      - --node-config
      - "partition-id=2 num-partitions=4 dataset-path='/home/partition_2.npz'"
    depends_on:
      - superlink
    volumes:
      - ./client_3:/home
    networks:
      - flower-net

  supernode-4:
    image: flwr/supernode:${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9097
      - --isolation
      - process
      - --node-config
      - "partition-id=3 num-partitions=4 dataset-path='/home/partition_3.npz'"
    depends_on:
      - superlink
    volumes:
      - ./client_4:/home
    networks:
      - flower-net

  # create one SuperExec service for each SuperNode to execute ClientApps
  superexec-clientapp-1:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: Dockerfile.client
      args:
        FLWR_VERSION: ${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-1:9094
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-1
    volumes:
      - ./client_1:/home
    networks:
      - flower-net

  superexec-clientapp-2:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: Dockerfile.client
      args:
        FLWR_VERSION: ${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-2:9095
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-2
    volumes:
      - ./client_2:/home
    networks:
      - flower-net

  superexec-clientapp-3:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: Dockerfile.client
      args:
        FLWR_VERSION: ${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-3:9096
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-3
    volumes:
      - ./client_3:/home
    networks:
      - flower-net

  superexec-clientapp-4:
    privileged: true
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: Dockerfile.client
      args:
        FLWR_VERSION: ${FLWR_VERSION:-1.22.0}
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode-4:9097
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-4
    volumes:
      - ./client_4:/home
    networks:
      - flower-net

networks:
  flower-net:
